name: teddyhunt
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3
  dio: ^3.0.9
  cached_network_image: ^2.0.0-rc
  image_picker: ^0.6.1+10
  url_launcher: ^5.4.2
  google_maps_flutter:
    git:
      url: https://github.com/everton-e26/plugins.git
      path: packages/google_maps_flutter
  location: ^2.3.5
  device_info: ^0.4.2+1
  geolocator: ^5.3.0
  shared_preferences: ^0.5.0
  progress_dialog: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

